In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.xls'))

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df['PhoneService'].unique()

array(['No', 'Yes'], dtype=object)

In [6]:
df['MultipleLines'].unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [13]:
df['NumberOfLines'] = np.where((df['MultipleLines']=='No phone service') | (df['MultipleLines']=='No'),'One','More than one')

In [14]:
df[['PhoneService','MultipleLines','NumberOfLines']].sample(5)

     PhoneService MultipleLines  NumberOfLines
3379          Yes            No            One
3158          Yes            No            One
2480          Yes           Yes  More than one
2444          Yes           Yes  More than one
5327          Yes            No            One

In [15]:
df['StreamingTV'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [16]:
df['StreamingMovies'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [19]:
df['StreamingTVOrMovies'] = np.where((df['StreamingMovies'] == 'Yes') | (df['StreamingTV'] == 'Yes'),'Yes','No')

In [20]:
df[['StreamingTV','StreamingMovies','StreamingTVOrMovies']].sample(10)

              StreamingTV      StreamingMovies StreamingTVOrMovies
6269                   No                   No                  No
703   No internet service  No internet service                  No
5676  No internet service  No internet service                  No
2523  No internet service  No internet service                  No
6340                  Yes                   No                 Yes
4249                   No                  Yes                 Yes
5429                   No                  Yes                 Yes
2568  No internet service  No internet service                  No
1183                  Yes                  Yes                 Yes
5489                   No                   No                  No

In [21]:
df['StreamingTVOrMovies'].unique()

array(['No', 'Yes'], dtype=object)